---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: cache-pull
  image: meltwater/drone-cache:v1.1.0
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  settings:
    restore: true
    cache_key: "cache"
    archive_format: "gzip"
    bucket: drone-cache
    endpoint: http://10.12.4.114:9000
    region: us-east-1
    path_style: true
    mount:
    - "go"
    - "cache"
#- name: vet
#  image: graytshirt/golang:0.0.5
#  environment:
#    GOPATH: "/drone/src/go"
#  commands:
#  - make vet
- name: lint
  image: golangci/golangci-lint:v1.31.0-alpine
  environment:
    GOPATH: "/drone/src/go"
    GOCACHE: "/drone/src/cache"
  commands:
  - golangci-lint run --timeout 5m -v --skip-dirs "mod|cache|tmp|go"
- name: sec
  image: securego/gosec:v2.4.0
  environment:
    GOPATH: "/drone/src/go"
    GOCACHE: "/drone/src/cache"
  commands:
  - gosec -exclude-dir mod -exclude-dir cache -exclude-dir tmp -exclude-dir go ./...
- name: build
  image: graytshirt/golang:0.0.6
  environment:
    GOPATH: "/drone/src/go"
    GOCACHE: "/drone/src/cache"
  commands:
  - make build
- name: e2e
  image: graytshirt/golang:0.0.6
  environment:
    GOPATH: "/drone/src/go"
    GOCACHE: "/drone/src/cache"
  commands:
  - make build
  - ./hyperctl VERSION
- name: cache-push
  image: meltwater/drone-cache:v1.1.0
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  settings:
    rebuild: true
    cache_key: "cache"
    archive_format: "gzip"
    bucket: drone-cache
    endpoint: http://10.12.4.114:9000
    region: us-east-1
    path_style: true
    mount:
    - "go"
    - "cache"

- name: release
  image: graytshirt/kaniko
  commands:
  - /executor
  when:
    ref:
    - refs/tags/**

---
kind: signature
hmac: 9454b6ab7372dcd3875da49d527750e55c701ecd673901afaf2e3e50a4c341c7

...
